controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

health:
   path: /health
   methods: [GET]
   defaults: { _controller: 'App\Controller\HealthCheckController::health' }

adicionar_livro:
   path: /v1/livros
   methods: [POST]
   defaults: { _controller: 'App\Controller\LivroController::cadastrar'}

buscar_livros:
   path: /v1/livros
   methods: [GET]
   defaults: { _controller: 'App\Controller\LivroController::getAll'}